//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZLPInstall.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZLPInstall.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZLPlayer End User License Agreement
        ///	Before to use this application, you must argee with the license agreement of the open source projects and ZLPlayer.
        ///	The open source projects include libfaad 2.7,libflac 1.2.1,libogg 1.2.2,libtta c++ 2.1,libvorbis 1.3.2,MAC_SDK 4.11,mpg123 1.13,tak 2.1,OptimFROG 4.910b,wavpack 4.60.1,mp4als RM23,libjpg and libpng.You can find the license agreement of these open source projects by search engine and find in their home page,or you can get them by send email:zhaojunlucky@q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string agreement {
            get {
                return ResourceManager.GetString("agreement", resourceCulture);
            }
        }
        
        internal static byte[] zh {
            get {
                object obj = ResourceManager.GetObject("zh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] zip {
            get {
                object obj = ResourceManager.GetObject("zip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZJA {
            get {
                object obj = ResourceManager.GetObject("ZJA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon ZLPlayer {
            get {
                object obj = ResourceManager.GetObject("ZLPlayer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
